import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/context/cartContext";
import { AddressProvider } from "@/context/addressContext";
import { UserProvider } from "@/context/userContext";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <AddressProvider>
            <CartProvider>
              {" "}
              <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
            </CartProvider>
          </AddressProvider>
        </UserProvider>
      </body>
    </html>
  );
}
